name: Python Package CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Change this to the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python setup.py test

    - name: Generate module status document
      run: python -m pch2csd gen_udo_status_doc

    - name: Commit and push changes to wiki
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git clone https://github.com/gleb812/pch2csd.wiki.git
        cp Module-implementation-status.md pch2csd.wiki/
        cd pch2csd.wiki
        git add Module-implementation-status.md
        # Check if there are changes before committing
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m 'Update Module Implementation Status'
          git push --quiet
        else
          echo "No changes to commit."
        fi

